In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
train1 = pd.read_csv('missingdead.csv', encoding='utf8')

train1.head(2)

,Web ID,Region of Incident,Reported day,Reported Month,Reported Year,Number Dead,Minimum Estimated Number of Missing,Total Dead and Missing,Number of Survivors,Number of Females,...,Number of Children,Cause of Death,Location Description,Information Source,Source Quality,Migration Route,URL,UNSD Geographical Grouping,Longitude,Latitude
0,52491,Mediterranean,14,Oct,2019,2,6,2,33,1,...,2,Drowning,"Off the coast of Altınova, Ayvalık, Balıkesir ...","IOM Turkey, Turkish Coast Guard",5,Eastern Mediterranean,"http://bit.ly/2IM85We, http://bit.ly/2IMOxAY, ...",Uncategorized,39.207629,26.683134
1,52496,Europe,14,Oct,2019,2,6,2,14,1,...,1,Drowning,"Bodies recovered on Le Touquet, Pas-de-Calais,...","Franceinfo, Le Monde",3,Western Europe,"http://bit.ly/2pm5ZW8, http://bit.ly/32kxFt6",Western Europe,50.524420,1.556037

In [3]:
df2 = train1.copy()

In [5]:
#Eliminamos columnas innecesarias
df2.drop(columns=['Web ID', 'URL'], inplace=True)

df2.dtypes

Region of Incident                             object
Reported day                                    int64
Reported Month                                  int64
Reported Year                                   int64
Number Dead                                     int64
Minimum Estimated Number of Missing             int64
Total Dead and Missing                          int64
Number of Survivors                             int64
Number of Females                               int64
Number of Males                                 int64
Number of Children                              int64
Cause of Death                                 object
Location Description                           object
Information Source                             object
Source Quality                                  int64
Migration Route                                object
UNSD Geographical Grouping                     object
Latitude                                      float64
Length                                        float64
Reported case                          datetime64[ns]
dtype: object

In [7]:
#Reordenamos las columnas

df2 = df2[['Reported case', 'Reported day','Reported Month','Reported Year',
          'Region of Incident', 'Number Dead',
       'Minimum Estimated Number of Missing', 'Total Dead and Missing',
       'Number of Survivors', 'Number of Females', 'Number of Males',
       'Number of Children', 'Cause of Death', 'Location Description',
       'Information Source', 'Source Quality', 'Migration Route',
       'UNSD Geographical Grouping', 'Latitude', 'Length']]

df2.head(2)

,Reported case,Reported day,Reported Month,Reported Year,Region of Incident,Number Dead,Minimum Estimated Number of Missing,Total Dead and Missing,Number of Survivors,Number of Females,Number of Males,Number of Children,Cause of Death,Location Description,Information Source,Source Quality,Migration Route,UNSD Geographical Grouping,Latitude,Length
0,2019-10-14,14,10,2019,Mediterranea,2,6,2,33,1,1,2,Drowning,"Off the coast of Altınova, Ayvalık, Balıkesir ...","IOM Turkey, Turkish Coast Guard",5,Eastern Mediterranea,Uncategorized,39.207629,26.683134
1,2019-10-14,14,10,2019,Europe,2,6,2,14,1,2,1,Drowning,"Bodies recovered on Le Touquet, Pas-de-Calais,...","Franceinfo, Le Monde",3,Western Europe,Western Europe,50.524420,1.556037

In [8]:
#Obtenemos un csv para entrenar

df2.to_csv('region2.csv', index=False)


df2.head()

,Reported case,Reported day,Reported Month,Reported Year,Region of Incident,Number Dead,Minimum Estimated Number of Missing,Total Dead and Missing,Number of Survivors,Number of Females,Number of Males,Number of Children,Cause of Death,Location Description,Information Source,Source Quality,Migration Route,UNSD Geographical Grouping,Latitude,Length
0,2019-10-14,14,10,2019,Mediterranea,2,6,2,33,1,1,2,Drowning,"Off the coast of Altınova, Ayvalık, Balıkesir ...","IOM Turkey, Turkish Coast Guard",5,Eastern Mediterranea,Uncategorized,39.207629,26.683134
1,2019-10-14,14,10,2019,Europe,2,6,2,14,1,2,1,Drowning,"Bodies recovered on Le Touquet, Pas-de-Calais,...","Franceinfo, Le Monde",3,Western Europe,Western Europe,50.524420,1.556037
2,2019-12-10,12,10,2019,US-Mexico Border,1,6,1,14,1,1,1,Drowning,"Río Bravo, near La Playita, Reynosa, Tamaulipa...","El Mañana, Milenio",3,Central America,Central America,26.144550,-98.332108
3,2019-11-10,11,10,2019,Central America,3,6,3,8,1,3,1,Drowning,"Off the coast of Tonalá, between Puerto Arista...","Instituto Nacional de Migración, El Universal,...",5,Central America,Central America,15.880321,-93.833002
4,2019-09-10,9,10,2019,Europe,3,6,3,12,1,1,1,Vehicle Accide,"Road near Areti, 40km northeast of Thessalonik...","IOM Greece, Ekathimerini",4,Southern Europe,Southern Europe,40.740769,23.256372